meta_product_name: "Goated."
meta_title: "Goated. - Say bêêêêêêê to new adventures"
meta_description: "take adventure by the horns"
meta_image: "https://res.cloudinary.com/rubberd/image/upload/v1654075412/offthecliff/logo-white_emkdhk.png" # should exist in `app/assets/images/`
twitter_account: "@purpledunoyer"   # required for Twitter Cards
