meta_product_name: "Goated."
meta_title: "Goated. - Say bêêêêêêê to new adventures"
meta_description: "take adventure by the horns"
meta_image: "https://res.cloudinary.com/rubberd/image/upload/v1654682533/offthecliff/logo-big_bz7qx4.png" # should exist in `app/assets/images/`
twitter_account: "@purpledunoyer"   # required for Twitter Cards
